---
- hosts: localhost
  connection: local
  pre_tasks:
    - name: Assign OS group
      group_by:
        key: "{{ ansible_facts['os_family'] | lower }}"
      tags: always
  roles:
    - { role: base,    tags: [base, packages] }
    - { role: aur,     tags: [aur, packages],  when: "ansible_facts['os_family'] == 'Archlinux'" }
    - { role: dev,     tags: [dev, packages] }
    - { role: sysctl,  tags: [sysctl, tuning] }
    - { role: chezmoi, tags: [chezmoi, dotfiles] }
    - { role: atuin,   tags: [atuin, services] }
