---
- name: Install atuin
  ansible.builtin.import_tasks: install.yml
  tags: [install]

- name: Configure atuin
  ansible.builtin.import_tasks: config.yml
  tags: [config]

- name: Include service tasks
  ansible.builtin.include_tasks: "service_{{ ws_service_manager }}.yml"
  when: atuin_sync_enabled
  tags: [services]
