---
- name: Assert chezmoi_repo_url is set
  assert:
    that: chezmoi_repo_url | length > 0
    fail_msg: "chezmoi_repo_url must be set (-e chezmoi_repo_url=...)"

- name: Initialize chezmoi
  command: "chezmoi init {{ chezmoi_init_args }} {{ chezmoi_repo_url }}"
  args:
    creates: "{{ ws_home }}/.local/share/chezmoi"
