---
- name: Install chezmoi
  ansible.builtin.import_tasks: install.yml
  tags: [install]

- name: Initialize chezmoi
  ansible.builtin.import_tasks: init.yml
  tags: [config]

- name: Apply chezmoi
  ansible.builtin.import_tasks: apply.yml
  tags: [config]
