---
- name: Apply sysctl settings (macOS)
  ansible.builtin.command:
    argv:
      - sysctl
      - -w
      - "{{ item.key }}={{ item.value }}"
  loop: "{{ sysctl_settings | dict2items }}"
  become: true
  changed_when: true
  tags: [config]
